import { ArrowLeft } from "lucide-react";
import Link from "next/link";

import { BRAND } from "@/lib/brand";

export const metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16 sm:px-8">
      <Link href="/" className="inline-flex items-center gap-1.5 text-small text-muted-foreground hover:text-foreground">
        <ArrowLeft className="h-4 w-4" /> Back to {BRAND.name}
      </Link>

      <h1 className="mt-8 text-title text-foreground sm:text-display">Privacy Policy</h1>
      <p className="mt-2 text-caption text-muted-foreground">Last updated {new Date().getFullYear()}</p>

      <div className="mt-10 space-y-8 text-small leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-heading text-foreground">What we store</h2>
          <p className="mt-2">
            {BRAND.name} stores exactly what it needs to build your career model: your profile
            (background, education, experience, skills), your stated goal, the skill-gap analyses and
            roadmaps generated from them, and any CV or profile document you submit for feedback.
          </p>
        </section>

        <section>
          <h2 className="text-heading text-foreground">Your control over your data</h2>
          <p className="mt-2">
            You can view everything stored about you at any time from Settings. You can delete specific
            data — such as your profile fields or an individual CV feedback round — independent of your
            account. You can delete your account entirely, which removes your identity and every piece
            of data associated with it.
          </p>
        </section>

        <section>
          <h2 className="text-heading text-foreground">How your data is used</h2>
          <p className="mt-2">
            Your data is used only to personalize your own experience — to generate your own analyses,
            roadmap, and feedback. It is never used to shape another user&apos;s experience by default.
          </p>
        </section>

        <section>
          <h2 className="text-heading text-foreground">AI processing</h2>
          <p className="mt-2">
            Skill-gap analyses, roadmaps, and CV feedback are generated by AI models processing your
            profile, goal, and submitted documents. Every AI-generated output is advisory — you retain
            final control over every action it recommends.
          </p>
        </section>

        <section>
          <h2 className="text-heading text-foreground">Contact</h2>
          <p className="mt-2">
            Questions about this policy or your data can be directed through your account settings.
          </p>
        </section>
      </div>
    </main>
  );
}
