"""add notification preferences and subscription cancellation reason

Revision ID: 68c38003a713
Revises: c2e1abb53237
Create Date: 2026-08-06 02:32:04.600824
"""
from alembic import op
import sqlalchemy as sa


revision = '68c38003a713'
down_revision = 'c2e1abb53237'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('muted_categories', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('subscriptions', sa.Column('cancellation_reason', sa.Text(), nullable=True, comment='FR-RENEW-2: optional, non-blocking — the user is never required to provide one.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'cancellation_reason')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
