"""add interview preparation tables

Revision ID: b192831432f0
Revises: 2a72b314d0d2
Create Date: 2026-08-10 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

revision = 'b192831432f0'
down_revision = '2a72b314d0d2'
branch_labels = None
depends_on = None

# Hand-written rather than autogenerated: this environment has no network
# path to the live database (Neon) to diff against, so this migration was
# built by hand from the model definitions (app/db/models.py's
# InterviewSession/InterviewQuestion/InterviewAnswer), following the exact
# same table/enum/index conventions autogenerate has produced for every
# prior migration in this project (compare 2a72b314d0d2, which this one is
# structurally closest to). `report_confidence` reuses the `confidencelevel`
# enum type created in the very first migration (3bb0f586eb34) —
# create_type=False so this migration does not attempt to CREATE TYPE a
# type that already exists.


def upgrade() -> None:
    op.create_table('interview_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('target_field', sa.String(), nullable=False),
    sa.Column('experience_level', sa.Enum('ENTRY', 'MID', 'SENIOR', name='interviewexperiencelevel'), nullable=False),
    sa.Column('interview_type', sa.Enum('BEHAVIORAL', 'TECHNICAL', 'MIXED', 'SCREENING', name='interviewtype'), nullable=False),
    sa.Column('target_company', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='interviewsessionstatus'), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('answer_quality', sa.Integer(), nullable=True),
    sa.Column('communication', sa.Integer(), nullable=True),
    sa.Column('structure_score', sa.Integer(), nullable=True),
    sa.Column('technical_readiness', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('areas_to_improve', sa.JSON(), nullable=False),
    sa.Column('recommended_practice', sa.JSON(), nullable=False),
    sa.Column('next_interview_recommendation', sa.Text(), nullable=False),
    sa.Column('report_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', create_type=False), nullable=True),
    sa.Column('report_confidence_reason', sa.Text(), nullable=False),
    sa.Column('report_grounded_on', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)

    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('INTRO', 'BEHAVIORAL', 'TECHNICAL', 'ROLE_SPECIFIC', 'RESUME_BASED', 'FOLLOW_UP', name='interviewquestioncategory'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_session_id'), 'interview_questions', ['session_id'], unique=False)

    op.create_table('interview_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('clarity_score', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('structure_score', sa.Integer(), nullable=False),
    sa.Column('feedback_note', sa.Text(), nullable=False),
    sa.Column('example_improved_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )


def downgrade() -> None:
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_interview_questions_session_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    sa.Enum(name='interviewquestioncategory').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interviewsessionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interviewtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interviewexperiencelevel').drop(op.get_bind(), checkfirst=True)
