"""add document_text to cv_feedback_rounds

Revision ID: c2e1abb53237
Revises: 3bb0f586eb34
Create Date: 2026-08-06 00:06:02.935428
"""
from alembic import op
import sqlalchemy as sa


revision = 'c2e1abb53237'
down_revision = '3bb0f586eb34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_feedback_rounds', sa.Column('document_text', sa.Text(), server_default='', nullable=False, comment='The actual submitted text — needed so FR-AICC-18 (view past rounds) and on-request explanation (RAI-4) can show/reground against what was actually submitted, not just a storage-path placeholder.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_feedback_rounds', 'document_text')
    # ### end Alembic commands ###
